config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to: "posts#index"

  resources :posts, only: %i[index]
  
  resources :users, only: %i[index show edit update] do
    resources :posts, only: %i[show new create edit update destroy] do
      resources :likes, only: %i[create destroy], module: :posts
      resources :comments, only: %i[create]
    end
    get :following, :followers, on: :member
    resource :relationship, only: %i[create destroy]
    collection do
      get :profile
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/lo'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  has_many :comments, dependent: :destroy
  validates :content, presence: true, length: {maximum: 140}

  has_many :likes_create_with_in_yesterday,
           -> { where(created_at: 1.day.ago.all_day) },
           class_name: 'Like'

  scope :recent, -> { order(created_at: :desc) }

  mount_uploader :image, PostUploader

  def writer?(user)
    self.user == user
  end

  def liked_user?(user)
    likes.find_by(user_id: user.id)
  end

  def self.likes_ranking_yesterday(limit = 10)
    Post.joins(:likes_create_with_in_yesterday)
      .group(:id)
      .order(Arel.sql('COUNT(likes.id) DESC'))
      .limit(limit)
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @post.likes.create!(user: current_user)
    @post.reload
  end

  def destroy
    @post.likes.find(params[:id]).destroy!
    @post.reload
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[new show edit create update destroy]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.where(user: current_user.timeline_ids ).recent
  end

  def show
  end

  def edit
  end

  def new
    @post = Post.new
  end

  def create
    @post = @user.posts.build(post_params)
    if @post.save
      redirect_to posts_path(@user)
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_url
  end

  private
  
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :image)
  end
end

app/views/posts/_form.html.haml
= simple_form_for([@user, @post]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .row
    .form-inputs.col
      = f.input :content, as: :text, input_html: {row: 4}
  .row
    .form-inputs.col
      = f.input :image, as: :image_preview, input_html: { preview_version: :thumbnail }
  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/posts/_post_list.html.haml
%ul.list-group
- posts.each do |post|
  %li.list-group-item
    .row
      .col.user_name= link_to post.user.name, user_path(post.user)
      %small.col-3.published.text-muted= l(post.created_at, format: :short)
    .row.m-1
      .col.content
        = simple_format(h(post.content))
        = image_tag post.image_url(:thumbnail) if post.image.present?

        = link_to '詳細', user_post_path(post.user, post)
    .row
      .col
        = render 'posts/likes/like_form', post: post if current_user != post.user
      .col.actions.text-right
        - if post.writer?(current_user)
          =link_to '編集', edit_user_post_path(post.user, post)
          \|
          =link_to '削除', user_post_path(post.user, post), method: :delete, data: {confirm: "削除しますか？"}

app/views/posts/edit.html.haml
= render 'form', post: @post

app/views/posts/index.html.haml
%h1 全体タイムライン

= render 'post_list', posts: @posts.includes(:user)

app/views/posts/new.html.haml
= render 'form', post: @post

app/views/posts/show.html.haml
%h1= @post.content

#images.m-3
  = link_to @post.image_url, target: :_blank do
    = image_tag @post.image_url(:thumbnail) if @post.image.present?
= render 'posts/likes/like_form', post: @post

%h3.mt-3 いいねしたユーザー
#liked_users.mt-4
  = render 'users/user_list', users: @post.liked_users

- if current_user == @post.user
  =link_to '編集', edit_user_post_path(@user, @post)
  \|
  =link_to '削除', user_post_path(@user, @post), method: :delete, data: {confirm: "削除しますか？"}

= render "comments/form", post: @post, comment: Comment.new

= render "comments/comment_list", comments: @post.comments.older
=link_to '戻る', posts_path