config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root to: "posts#index"

  resources :posts, only: %i[index]
  
  resources :users, only: %i[index show edit update] do
    resources :posts, only: %i[show new create edit update destroy] do
      resources :likes, only: %i[create destroy], module: :posts
      resources :comments, only: %i[create]
    end
    get :following, :followers, on: :member
    resource :relationship, only: %i[create destroy]
    collection do
      get :profile
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/lo'
  end
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-light.bg-light
  - if user_signed_in?
    = link_to '140文字のフリーダム', root_path, class: 'nav-item active'
    = link_to 'ユーザー一覧', users_path, class: 'nav-item nav-link'
    = link_to '投稿する', new_user_post_path(current_user), class: 'nav-item nav-link'
    = link_to "プロフィール(#{current_user.name})", profile_users_path, class: 'nav-item nav-link'
    = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-item nav-link'
  - else
    = link_to 'ログイン', new_user_session_path, class: 'nav-item nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 140文字のフリーダム
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container.mt-3
      - if alert
        %p.alert.alert-danger= alert
      - elsif notice
        %p.alert.alert-success= notice
      = yield